CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(3) NOT NULL,
    env VARCHAR(10) NOT NULL,
    public_key CHAR(16) NOT NULL,
    hash VARCHAR(255) NOT NULL,
    scopes JSONB NOT NULL,
    expires_at TIMESTAMPTZ NULL,
    revoked_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NULL,
    last_used_at TIMESTAMPTZ NULL,
    name VARCHAR(100) NULL,
    created_by VARCHAR(100) NULL,
    last_used_ip VARCHAR(64) NULL,
    last_used_user_agent VARCHAR(512) NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_api_keys_public_key
    ON api_keys (public_key);
