CREATE TABLE api_keys (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    app VARCHAR(3) NOT NULL,
    env VARCHAR(10) NOT NULL,
    public_key CHAR(16) NOT NULL,
    hash VARCHAR(128) NOT NULL,
    scopes JSON NOT NULL,
    expires_at DATETIME(6) NULL,
    revoked_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NULL,
    last_used_at DATETIME(6) NULL,
    name VARCHAR(100) NULL,
    created_by VARCHAR(100) NULL,
    last_used_ip VARCHAR(45) NULL,
    last_used_user_agent VARCHAR(255) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_api_keys_public_key (public_key),
    KEY ix_api_keys_app_env (app, env),
    KEY ix_api_keys_revoked_expires (revoked_at, expires_at),
    CONSTRAINT chk_api_keys_app CHECK (app REGEXP '^[a-z0-9]{1,3}$'),
    CONSTRAINT chk_api_keys_env CHECK (env REGEXP '^[a-z0-9_-]{1,10}$')
);
